### ISSUE TITLE
Passing objects to routes.

### ISSUE THREAD

**Issue by nonameplum** [jwalapr/Routing#37]
Hi,

Great framework! I read documentation and I wonder whether there is possibility to pass object to the route? In the case when we want to pass object (model) from one view controller to another? I think about using your library as a coordinator with companion of the MVVM architecture. But without passing real object I will be uncomfortable to use. Have you seen this example of the MVVM-C (Coordinator)? I think that with your library it could be moved forward with benefit of the deep linking.

**Comment by jwalapr** [comment]
It's a thought I've been open to doing as well! Do you mind linking the example you mentioned. For now I figured the setup block or setup protocol method could be used to achieve something similar. It would definitely make it more on pair with other web routing libraries.

**Comment by nonameplum** [comment]
Ahh sorry I forgot to put the link -> https://github.com/macdevnet/mvvmc-demo .
