### ISSUE TITLE
Caching of routes opened

### ISSUE THREAD

**Issue by jwalapr** [jwalapr/Routing#44]
Route results of #open should be cached. Calls to #map or #proxy should invalidate the cache.

**Comment by nonameplum** [comment]
What is purpose?

**Comment by jwalapr** [comment]
Just a thought so we don't have to iterate through all the routes in subsequent calls. However, thinking more about it may not be worth it as an application will typically have a small amount of routes so the time to iterate through all them may be negligible.

**Comment by nonameplum** [comment]
Yeah even 100+ routes should not affect performance.

**Comment by jwalapr** [comment]
agreed, i'm closing this.
